"""Pluggable file storage for uploaded media (myth photo albums).

The default backend writes to the LOCAL filesystem under UPLOAD_FOLDER and
returns RELATIVE url paths like ``uploads/myths/<myth_id>/<name>.jpg`` — the
web frontend resolves those against NEXT_PUBLIC_API_BASE_URL (imageUrlFor),
and the Flask ``/uploads/<path>`` route serves them.

To move to cloud storage later, implement StorageBackend (e.g. an
S3-compatible class whose ``url()`` returns absolute URLs), register it in
``get_storage()``, and set STORAGE_BACKEND in the environment. Routes and
models never touch the filesystem directly, so nothing else changes.
"""

import os
import uuid
from abc import ABC, abstractmethod

from flask import current_app


class StorageBackend(ABC):
    @abstractmethod
    def save(self, file_storage, key):
        """Persist a werkzeug FileStorage under ``key``; return the url path
        to store in the DB (relative for local, absolute for cloud)."""

    @abstractmethod
    def delete(self, key):
        """Remove the stored file; a missing file is a no-op."""

    @abstractmethod
    def url(self, key):
        """The url path clients should use for ``key``."""


class LocalStorage(StorageBackend):
    """Files under app.config['UPLOAD_FOLDER'], served by GET /uploads/<key>."""

    def _root(self):
        return current_app.config['UPLOAD_FOLDER']

    def _path(self, key):
        # Keys are generated by make_photo_key (uuid names) — never user input —
        # but normalize defensively so a bad key can't escape the upload root.
        root = os.path.normpath(self._root())
        path = os.path.normpath(os.path.join(root, key))
        if not path.startswith(root + os.sep):
            raise ValueError('invalid storage key')
        return path

    def save(self, file_storage, key):
        path = self._path(key)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        file_storage.save(path)
        return self.url(key)

    def delete(self, key):
        try:
            os.remove(self._path(key))
        except FileNotFoundError:
            pass

    def url(self, key):
        return f"uploads/{key.replace(os.sep, '/')}"


def get_storage():
    backend = current_app.config.get('STORAGE_BACKEND', 'local')
    if backend == 'local':
        return LocalStorage()
    raise RuntimeError(f'Unknown STORAGE_BACKEND: {backend}')


def allowed_extension(filename):
    """Lowercased extension if allowlisted, else None."""
    if not filename or '.' not in filename:
        return None
    ext = filename.rsplit('.', 1)[1].lower()
    allowed = current_app.config.get('ALLOWED_IMAGE_EXTENSIONS', set())
    return ext if ext in allowed else None


def make_photo_key(myth_id, ext):
    """Storage key for a new photo: myths/<myth_id>/<uuid>.<ext>.

    Only the (validated) extension comes from the client; the name is a uuid,
    so filenames never collide and unicode/unsafe original names don't matter.
    """
    return f"myths/{myth_id}/{uuid.uuid4().hex}.{ext}"


def key_for_url(url):
    """Inverse of LocalStorage.url: the storage key for a local ``uploads/...``
    url, or None when the url is external (absolute/cloud) and shouldn't be
    deleted from local disk."""
    if url and url.startswith('uploads/'):
        return url[len('uploads/'):]
    return None
